version: '3'

services:
  orders-db:
    image: postgres:16.2
    container_name: orders_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
